# -*- coding: utf-8 -*-
"""Day20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YfbZ3p6sBpxEhvwBDQs7hOKNhVbtqc9s
"""

a = 3
b = 5

"""Print my introduction"""

print("Hi! My name is Praneta.")



"""Write you introduction(Name, School)"""

print("Hi! My name is Praneta. My school name is St. Lawrence")

"""Create some variables"""

a = 10
b = "Apple"

"""Print (10 + 5)"""

print( 10 + 5)

"""Create list and print it"""

my_list = ["Apple", "Banana", 5 , 10]

print(my_list)

"""Pyhton Polymorphism - Polymorphism means "many forms" and in programming it refers to methods/
functions/ operators with same name that can be executed on many objects or classes.

Function Polymorphism
len() function

String
"""

x = "Hello World!"
print(len(x))

"""Tuple"""

mytuple = ("Apple", "banana", "cherry")
print(len(mytuple))

"""Dictionary"""

thisdict = {
    "brand": "Ford",
    "model": "Mustang",
    "year": 1964
}

print(len(thisdict))

"""Class Polymorphism

Different classes with the same methods:
"""

class Car:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Drive!")

class Boat:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Sail!")

class Plane:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Fly!")


car1 = Car("Fard", "Mustang")
boat1 = Boat("Ibiza", "Touring 20")
plane1 = Plane("Boeing", "747")

for x in (car1, boat1, plane1):
  x.move()
