# -*- coding: utf-8 -*-
"""Day28.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-GWOAhMOWJqzC01HrodKysuiH9s7LG8z

User Input

Syntax for User Input:

inp = input('STATEMENT')
"""

username = input("Enter username")
print("Username is:" + username)

"""Q.1) Write a program which takes interger as user input.

Q.2) Write a program which gives output as float value.

Q.3) Write a program, take user input by creating if and else
"""

prompt1 = input("Do you like cake? Type yes or no")
if prompt1 == 'yes':
  print("We have chocolate cake")
elif prompt1 == 'no':
  print("Other options")

"""Q. Draw a Star using turtle model."""