# -*- coding: utf-8 -*-
"""day23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AYXy6-B1-Y3mHLmFZ8bgvbRONAm96s0w

###Python Scope
Scope - A variable is only available from inside the region it is created.

1) Local Scope

eg) A variable created inside a function is available inside that function:
"""

def myfunc():
  x = 300
  print(x)

myfunc()

"""Function Inside Function

eg) The local variable can be accessed from a function within the function:
"""

def myfunc():
  x = 300
  def myinnerfunc():
    print(x)

  myinnerfunc()
myfunc()

"""eg) A variable created outside of a function is global and can be used by anyone:"""

x = 300

def myfunc():
  print(x)

myfunc()

print(x)

"""Naming Variables

eg) The function will print the local x, and then the code will print the global x
"""

x = 300

def myfunc():
  x = 200
  print(x)

myfunc()

print(x)

"""Global Keyword

eg) If you use the gloabal keyword, the variable belongs to the global scope:
"""

def myfunc():
  global x
  x = 300

myfunc()

print(x)

"""eg) To change the value of a gloabal variable inside a function, refer to the variable by using the global keyword:"""

x = 300

def myfunc():
  global x
  x = 200

myfunc()
print(x)