# -*- coding: utf-8 -*-
"""Day31.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kWYkU1ZcUf5cPwcmFEiHob86wWoMdJMJ

**Data Types in NumPy**

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
0 - object
s - string
u - unicode string
v - fixed chunk of memory for other types

Checking the Data Type of an array:
- NumPy array object has a property 'dtype' that returns the data type of an array

eg. Write a Program to get the data type of an array object:
"""

import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

"""eg. Write a Program to get data type of an array object:
['apple', 'banana', 'cheery']

**Creating Arrays with a Defined Data TYpes**

eg. Write a program to create an array with data type string:
"""

import numpy as np
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

"""What if a value can not be converted:
It will give an error called 'ValueError'

eg. Write a Program for a non integer string like 'a' can not be converted to integer(will raise an error)
"""

import numpy as np
arr = np.array(['a', '2', '3'], dtype='i')

"""**Converting Data type on Existing Arrays:**
astype() - we can use this to change the data type of an existing array, this helps us to make a copy of the array and then it allows us to specify the datat type as a parameter.

eg. Write a program to change data type from float to interger by using 'i' as parameter value:
"""

import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

"""eg.) Write a program to change data type from float to integer by using 'int' as parameter value:"""